services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - env/local/.env.docker
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - env/local/.env.docker
    ports:
      - "${PGADMIN_PORT:-8080}:80"

volumes:
  pgdata: